var works = [
    {
      "folderImgName": "apolo",
      "title": "APOLO",
      "description": "El jugador toma el papel de un tripulante de la nave Apolo que se dirige hacia la Luna. En el trascurso del viaje el jugador tiene que ir completando unas serie de tareas de mantenimiento ingresando unos comandos a la computadora de abordo. El objetivo es llegar a salvo al destino.",
      "features": "Mantener la nave estable para llegar al objetivo. Revisar constantemente los instrumentos de la nave.",
      "tech0": "C++",
      "tech1": "",
      "tech2": "",
      "tech3": "",
      "tech4": "",
      "date": 2016,
      "gender": "RPG",
      "language": "Español",
      "type": "Demo",
      "distribution": "itchi.io",
      "os": "Windows 7+",
      "processor": "2 GHz",
      "memory": "",
      "graphics": "",
      "storage": "5 MB",
      "net": "",
      "notes": "",
      "staff": "Programación, game design e ilustración por Darío Ciarlantini.",
      "ssnumber": 4
    },
    {
      "folderImgName": "dir",
      "title": "title",
      "description": "des",
      "features": "",
      "tech0": "tech",
      "tech1": "tech",
      "tech2": "tech",
      "tech3": "tech",
      "tech4": "tech",
      "date": "date",
      "gender": "gen",
      "language": "",
      "type": "tp",
      "distribution": "dt",
      "os": "mc",
      "processor": 90,
      "memory": 10,
      "graphics": 10,
      "storage": "st",
      "net": "nt",
      "notes": "no",
      "staff": "dc",
      "ssnumber": 0
    }
  ]