var works = [
  {
    "fullTitle": "APOLO",
    "title": "APOLO",
    "folderName": "apolo",
    "banner": "TRUE",
    "iframe": "",
    "description": "El jugador toma el papel de un tripulante de la nave Apolo que se dirige hacia la Luna. En el trascurso del viaje el jugador tiene que ir completando unas serie de tareas de mantenimiento ingresando unos comandos a la computadora de abordo. El objetivo es llegar a salvo al destino.",
    "shortDescription": "Conduce el modulo lunar Apolo. Completa una serie de tareas e intenta llegar vivo al destino. ¡La Luna!",
    "features": "Mantener la nave estable para llegar al objetivo;Revisar constantemente los instrumentos de la nave",
    "techtags": "C++",
    "date": 2016,
    "version": 1,
    "gender": "RPG",
    "language": "Español",
    "type": "Demo",
    "os": "Windows 7+",
    "processor": "2 GHz",
    "memory": "-",
    "graphics": "-",
    "storage": "5 MB",
    "net": "-",
    "notes": "-",
    "staff": "Programación, game design e ilustración por Darío Ciarlantini.",
    "ssNumber": 4,
    "link1": "https://ciarlantinid.itch.io/apolo",
    "link2": "",
    "link3": "",
    "link4": "",
    "dateAdded": "1/01/2018",
    "category": "videogame"
  },
  {
    "fullTitle": "I Love My Dinosaur!",
    "title": "I Love My Dinosaur!",
    "folderName": "ilovemydinosaur",
    "banner": "TRUE",
    "iframe": "",
    "description": "¡Cuida a tu dinosaurio de las distintas entidades del gobierno que quiere quitartelo! Juega mini juegos para mantenerlo con vida y hacerlo feliz.",
    "shortDescription": "Cuida a tu dinosaurio de las entidades del gobierno que quiere quitartelo! Mantenerlo con vida y hacerlo feliz.",
    "features": "Cuida a tu dinosaurio de los agentes del gobierno;Mantenlo con vida dando le alimentos y medicinas;Juega minijuegos para ganar monedas y comprar cosas para tu dinosaurio;Usa trampas para defenderlo",
    "techtags": "Unity;C#",
    "date": 2019,
    "version": "pre-ALFA",
    "gender": "Tamagotchi",
    "language": "Multi",
    "type": "Demo",
    "os": "Windows 10 / iOS",
    "processor": "-",
    "memory": "-",
    "graphics": "-",
    "storage": "-",
    "net": "-",
    "notes": "-",
    "staff": "Programación / Game Design: Santiago Pérez y Darío Ciarlantini. Ilustraciones: Darío Ciarlantini",
    "ssNumber": 3,
    "link1": "https://github.com/ELDUODINAMITA/I-Love-my-Dinosaur",
    "link2": "",
    "link3": "",
    "link4": "",
    "dateAdded": "1/01/2018",
    "category": "videogame"
  },
  {
    "fullTitle": "Lunar Lander",
    "title": "Lunar Lander",
    "folderName": "lunarlander",
    "banner": "TRUE",
    "iframe": "",
    "description": "Usa tus habilidades para aterrizar en la superficie de la Luna. Tienes que ser cuidadoso. Solo un descenso lento y en la posición correcta te permitirá ganar este clásico de Atari.",
    "shortDescription": "Usa tus habilidades para aterrizar en la superficie de la Luna. Solo un descenso lento suave te permitirá ganar.",
    "features": "Hay que aterrizar la nave de forma vertical. Tener en cuenta el ángulo de inclinación;La gasolina es limitada y tiene que durar toda la partida, a menos que estes dispuesto a perder una vida;El tiempo también es limitado, pero uno tiene un buen margen para llegar al objetivo",
    "techtags": "Unity;C#",
    "date": 2017,
    "version": "1.0.2",
    "gender": "Arcade",
    "language": "Ingles",
    "type": "Demo",
    "os": "Windows 7+ / MacOS 10.6+",
    "processor": "2 GHz",
    "memory": "-",
    "graphics": "50 MB",
    "storage": "50 MB",
    "net": "-",
    "notes": "-",
    "staff": "Programación, game design e ilustración por Darío Ciarlantini. Música del Ménu por Jonn Serrie. Música en juego por Epicurus.",
    "ssNumber": 4,
    "link1": "https://ciarlantinid.itch.io/lunarlander",
    "link2": "",
    "link3": "",
    "link4": "",
    "dateAdded": "1/01/2018",
    "category": "videogame"
  },
  {
    "fullTitle": "Jugger Hound",
    "title": "Jugger Hound",
    "folderName": "juggerhound",
    "banner": "TRUE",
    "iframe": "",
    "description": "Adaptación de Megaman. El jugador tiene que desplazarse por el escenario disparando a los enemigos y evitar que estos te infrinja daño. Al final del nivel tendrá que enfrentarse a un jefe final para conseguir la victoria.",
    "shortDescription": "Tienes que desplazarse por el escenario disparando a los enemigos y evitando que ello te infrinja daño.",
    "features": "Avanzar por el nivel destruyendo a los enemigos;Pudes recuperar vida obteniendo botiquines dispersos por el escenario;Al final del nivel se tiene que derrotar a un Boss",
    "techtags": "HaxeFlixel",
    "date": 2016,
    "version": "ALFA",
    "gender": "Demo",
    "language": "Ingles",
    "type": "Demo",
    "os": "Widnows 7+",
    "processor": "-",
    "memory": "-",
    "graphics": "-",
    "storage": "50 MB",
    "net": "-",
    "notes": "-",
    "staff": "Desarrollado por Sebastian Sforzini, Takunori Kasai, Darío Ciarlantini. Idea original: Sebastian Sforzini",
    "ssNumber": 4,
    "link1": "https://ciarlantinid.itch.io/juggerhound",
    "link2": "",
    "link3": "",
    "link4": "",
    "dateAdded": "1/01/2018",
    "category": "videogame"
  },
  {
    "fullTitle": "BreakBoot",
    "title": "BreakBoot",
    "folderName": "breakboot",
    "banner": "TRUE",
    "iframe": "",
    "description": "El objetivo es descifrar la contraseña del sistema. Para eso, es necesario leer la información guardada en la memoria. Ahí se encuentran los caracteres de la contraseña. La herramienta de Hacking ayuda al jugador con pistas, pero los intentos son limitados.",
    "shortDescription": "Descifra la contraseña. Lee la información en la pantalla y  encuentran los caracteres en esta herramienta de hacking.",
    "features": "Obtener la contraseña escondida dentro del código;Tienes una cantidad limitada de oportunidades para descubirir la contraseña;Cada vez pierdas una oportunidad, se obtiene una ayuda",
    "techtags": "C#",
    "date": 2015,
    "version": 1,
    "gender": "Puzzle",
    "language": "Español",
    "type": "Demo",
    "os": "Windows 7+",
    "processor": "-",
    "memory": "-",
    "graphics": "-",
    "storage": "5 MB",
    "net": "-",
    "notes": "-",
    "staff": "Programación, game design e ilustración por Darío Ciarlantini.",
    "ssNumber": 3,
    "link1": "https://ciarlantinid.itch.io/breakboot",
    "link2": "",
    "link3": "",
    "link4": "",
    "dateAdded": "1/01/2018",
    "category": "videogame"
  },
  {
    "fullTitle": "Generala semi-automatica en Javascript",
    "title": "Generala JS",
    "folderName": "generalajs",
    "banner": "",
    "iframe": "TRUE",
    "description": "Generala desarrollada en Javascript que funciona con solo un botón de manera casi automatica.",
    "shortDescription": "Generala desarrollada en Javascript que funciona con solo un botón de manera casi automatica.",
    "features": "Un solo botón de juego; Reinicia la partida y guarda el mejor puntaje temporalmente.",
    "techtags": "HTML 5;Javascript",
    "date": 2018,
    "version": 1,
    "gender": "Clicker",
    "language": "Ingles",
    "type": "Demo",
    "os": "-",
    "processor": "-",
    "memory": "-",
    "graphics": "-",
    "storage": "-",
    "net": "-",
    "notes": "Navegador compatible con CSS 3, HTML 5 y Javascript.",
    "staff": "Programación y Diseño: Darío Ciarlantini",
    "ssNumber": 0,
    "link1": "https://github.com/CiarlantiniD/JSgenerala",
    "link2": "",
    "link3": "",
    "link4": "",
    "dateAdded": "10/10/2018",
    "category": "javascript"
  },
  {
    "fullTitle": "Calculadora en Javascript",
    "title": "Calculadora JS",
    "folderName": "calculadorajs",
    "banner": "",
    "iframe": "TRUE",
    "description": "Calculadora simple desarrollada en Javascript. Práctica del lenguaje de programación y diseño responsibe.",
    "shortDescription": "Calculadora simple desarrollada en Javascript. Práctica del lenguaje de programación y diseño responsibe.",
    "features": "Optiones de Suma, Resta, Multiplicación y División;Diseño responsive",
    "techtags": "HTML 5;Javascript",
    "date": 2018,
    "version": 1,
    "gender": "App",
    "language": "-",
    "type": "Demo",
    "os": "-",
    "processor": "-",
    "memory": "-",
    "graphics": "-",
    "storage": "-",
    "net": "-",
    "notes": "Navegador compatible con CSS 3, HTML 5 y Javascript.",
    "staff": "Programación y Diseño: Darío Ciarlantini",
    "ssNumber": 0,
    "link1": "https://github.com/CiarlantiniD/JScal",
    "link2": "",
    "link3": "",
    "link4": "",
    "dateAdded": "1/01/2018",
    "category": "javascript"
  },
  {
    "fullTitle": "Formulario Simple en Bootstrap",
    "title": "Bootstrap Form",
    "folderName": "bootstrapform",
    "banner": "",
    "iframe": "TRUE",
    "description": "Formulario simple con las opciones que provee bootstrap.",
    "shortDescription": "Formulario simple con las opciones que provee bootstrap.",
    "features": "Uso de biblioteca multiplataforma Bootstrap",
    "techtags": "HTML 5;Bootstrap",
    "date": 2018,
    "version": "BETA",
    "gender": "Form",
    "language": "Español",
    "type": "Demo",
    "os": "-",
    "processor": "-",
    "memory": "-",
    "graphics": "-",
    "storage": "-",
    "net": "-",
    "notes": "Navegador compatible con CSS 3, HTML 5 y Javascript.",
    "staff": "Diseño: Darío Ciarlantini",
    "ssNumber": 0,
    "link1": "http://ciarlantini.com.ar/bootstrapform/index.html",
    "link2": "",
    "link3": "",
    "link4": "",
    "dateAdded": "1/01/2018",
    "category": "javascript"
  },
  {
    "fullTitle": "Counter Strike Map",
    "title": "Counter Strike Map",
    "folderName": "counterstrikemap",
    "banner": "TRUE",
    "iframe": "",
    "description": "Concepto de mapa para Counter Strike en modalidad “Plantar la Bomba” realizado en Unity. El objetivo del proyecto es emular la disposición de un mapa de CS siguiendo ciertas reglas de diseño.",
    "shortDescription": "Concepto de mapa para Counter Strike en modalidad “Plantar la Bomba” realizado en Unity.",
    "features": "Mapa pensado para Counter Strike Source ó Global Offensive;Formato de mapa tipo Plantar la Bomba en uno de los sitios;Posee documentación de intención y estética del mapa",
    "techtags": "Unity",
    "date": 2017,
    "version": 1,
    "gender": "Map",
    "language": "-",
    "type": "Concept",
    "os": "-",
    "processor": "-",
    "memory": "-",
    "graphics": "-",
    "storage": "-",
    "net": "-",
    "notes": "Es necesario tener Unity 3D versión 2017.2",
    "staff": "Diseñado por Darío Ciarlantini.",
    "ssNumber": 5,
    "link1": "https://github.com/CiarlantiniD/Counter-Strike-Map",
    "link2": "",
    "link3": "",
    "link4": "",
    "dateAdded": "1/01/2018",
    "category": "gamedesign"
  },
  {
    "fullTitle": "Script FFmpeg",
    "title": "Script FFmpeg",
    "folderName": "scriptffmpeg",
    "banner": "",
    "iframe": "",
    "description": "Script basado en Bash para realizar transcodificaciones de diferentes tipos de archivos con FFmpeg en terminal de Linux.",
    "shortDescription": "Script basado en Bash para realizar transcodificaciones de diferentes tipos de archivos con FFmpeg en terminal de Linux.",
    "features": "Soporte para formato AVI, MOV, MXF;Transcoficicación de video a diferentes formatos;Extracción de Thumbnail en PNG;Concatación de videos;Sistema de LOG;Cálculo estimado de tiempo para los procesos",
    "techtags": "Bash;FFmpeg",
    "date": 2017,
    "version": "ALFA",
    "gender": "Tool",
    "language": "Español",
    "type": "Tool",
    "os": "Linux",
    "processor": "2 GHz",
    "memory": "-",
    "graphics": "-",
    "storage": "20 MB",
    "net": "-",
    "notes": "Es necesario tener instalado FFmpeg y MediaInfo desde terminal.",
    "staff": "Desarrollado por Darío Ciarlantini.",
    "ssNumber": 0,
    "link1": "https://github.com/CiarlantiniD/ServerScripting",
    "link2": "",
    "link3": "",
    "link4": "",
    "dateAdded": "1/01/2018",
    "category": "scripting"
  },
  {
    "fullTitle": "Script Presentes",
    "title": "Script Presentes",
    "folderName": "scriptpresentes",
    "banner": "",
    "iframe": "",
    "description": "Script para enviar un mail atravez de Gmail como una plantilla del estado de presentes.",
    "shortDescription": "Script para enviar un mail atravez de Gmail como una plantilla del estado de presentes.",
    "features": "Script basado en la plataforma de Google;Plantilla para facilitar el envio por Gmail",
    "techtags": "Gscript",
    "date": 2017,
    "version": 2.7,
    "gender": "Script",
    "language": "Español",
    "type": "Tool",
    "os": "-",
    "processor": "-",
    "memory": "-",
    "graphics": "-",
    "storage": "-",
    "net": "-",
    "notes": "Se necesita navegador compatible con Google Drive, Cuenta en Google y Conexión a Internet.",
    "staff": "Desarrollado por Darío Ciarlantini.",
    "ssNumber": 0,
    "link1": "https://github.com/CiarlantiniD/Presentes",
    "link2": "",
    "link3": "",
    "link4": "",
    "dateAdded": "1/01/2018",
    "category": "scripting"
  }
]